//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public string ApplicationID { get; set; }
        public string PanCard { get; set; }
        public string VoterID { get; set; }
        public string SalarySlip { get; set; }
        public string LOA { get; set; }
        public string BuilderNOC { get; set; }
        public string SaleAgreement { get; set; }
        public string AdminID { get; set; }
        public string BankAccount_Statement { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual CustomerApplication CustomerApplication { get; set; }
    }
}
