//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackStatu
    {
        public string ApplicationID { get; set; }
        public string AdminID { get; set; }
        public string Contact { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string LoanStatus { get; set; }
        public Nullable<System.DateTime> LoanApprovalDate { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual CustomerApplication CustomerApplication { get; set; }
    }
}
